# frozen_string_literal: true

ruby '2.7.3'
source 'https://rubygems.org'

gem 'awesome_print', '~> 1.9', '>= 1.9.2'
gem 'byebug', '~> 11.1', '>= 11.1.3'
gem 'guard', '~> 2.17'
gem 'guard-rspec', '~> 4.7', '>= 4.7.3'
gem 'humanize', '~> 2.5', '>= 2.5.1'
gem 'pry', '~> 0.13.1'
gem 'rspec'
gem 'rubocop', '~> 1.15'
