// https://projecteuler.net/problem=44

// Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

// Answer: 5482660

// Authored by: Tim Varley 💘
// Assisted-by: Grok Code Fast via Crush 💘 <crush@charm.land>

#include <iostream>
#include <vector>
#include <set>
#include <cmath>
#include <climits>

static bool is_pentagonal(long long n) {
    double k = (1 + sqrt(1 + 24.0 * n)) / 6;
    return k == floor(k);
}

long long pentagon_numbers() {
    std::vector<long long> pent;
    for (long long n = 1; n < 3000; n++) {
        long long p = n * (3 * n - 1) / 2;
        pent.push_back(p);
    }
    long long min_diff = LLONG_MAX;
    for (size_t i = 0; i < pent.size(); i++) {
        for (size_t j = i + 1; j < pent.size(); j++) {
            long long sum_p = pent[i] + pent[j];
            long long diff_p = pent[j] - pent[i];
            if (is_pentagonal(sum_p) && is_pentagonal(diff_p)) {
                if (diff_p < min_diff) min_diff = diff_p;
            }
        }
    }
    return min_diff;
}

#if ! defined UNITTEST_MODE
int main(int argc, char const *argv[]) {
    std::cout << pentagon_numbers() << std::endl;
}
#endif // UNITTEST_MODE