// https://projecteuler.net/problem=45

// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle 	 Tn=n(n+1)/2 	 1, 3, 6, 10, 15, ...

// Pentagonal 	 Pn=n(3n-1)/2 	 1, 5, 12, 22, 35, ...

// Hexagonal 	 Hn=n(2n-1) 	 1, 6, 15, 28, 45, ...

// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.

// Answer: 1533776805

// Authored by: Tim Varley 💘
// Assisted-by: Grok Code Fast via Crush 💘 <crush@charm.land>

#include <iostream>
#include <cmath>

long long triangular_pentagonal_hexagonal() {
    for (long long n = 144; ; n++) {
        long long h = n * (2 * n - 1);
        double k = (1 + sqrt(1 + 24.0 * h)) / 6;
        if (k == floor(k)) {
            return h;
        }
    }
    return 0;
}

#if ! defined UNITTEST_MODE
int main(int argc, char const *argv[]) {
    std::cout << triangular_pentagonal_hexagonal() << std::endl;
}
#endif // UNITTEST_MODE