// https://projecteuler.net/problem=61

// Cyclical Figurate Numbers

// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
// Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...
// Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...
// Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...
// Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...
// Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...
// Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...
// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
// 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
// 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
// 3. This is the only set of 4-digit numbers with this property.
// Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

// Answer: 28684

// Execution time: ~3ms on modern hardware

// Optimizations: Generate all 4-digit polygonal numbers, use prefix maps for efficient lookup, backtracking to find cyclic chain
// Interesting notes: AI-generated solution using combinatorial search with early termination

#include <iostream>
#include <vector>
#include <set>
#include <functional>

int cyclical_figurate_numbers() {
    // Generate all 4-digit polygonal numbers for each type
    std::vector<std::vector<int>> polys(9); // index 3-8 for types
    
    auto gen_poly = [&](int type, auto formula) {
        for (int n = 1; ; ++n) {
            int num = formula(n);
            if (num >= 10000) break;
            if (num >= 1000) polys[type].push_back(num);
        }
    };
    
    gen_poly(3, [](int n){ return n*(n+1)/2; }); // triangle
    gen_poly(4, [](int n){ return n*n; }); // square
    gen_poly(5, [](int n){ return n*(3*n-1)/2; }); // pentagonal
    gen_poly(6, [](int n){ return n*(2*n-1); }); // hexagonal
    gen_poly(7, [](int n){ return n*(5*n-3)/2; }); // heptagonal
    gen_poly(8, [](int n){ return n*(3*n-2); }); // octagonal
    
    // Create maps from first two digits to numbers for each type
    std::vector<std::vector<std::vector<int>>> by_prefix(9);
    for (int t = 3; t <= 8; ++t) {
        by_prefix[t].resize(100);
        for (int num : polys[t]) {
            int prefix = num / 100;
            by_prefix[t][prefix].push_back(num);
        }
    }
    
    // Find the cycle
    std::function<bool(std::vector<int>&, std::set<int>&, int)> find_cycle = [&](std::vector<int>& current, std::set<int>& used_types, int start_suffix) -> bool {
        if (current.size() == 6) {
            // Check if last connects to first
            int last = current.back() % 100;
            int first = current[0] / 100;
            return last == first;
        }
        
        int next_prefix = current.back() % 100;
        for (int t = 3; t <= 8; ++t) {
            if (used_types.count(t)) continue;
            for (int num : by_prefix[t][next_prefix]) {
                current.push_back(num);
                used_types.insert(t);
                if (find_cycle(current, used_types, start_suffix)) return true;
                used_types.erase(t);
                current.pop_back();
            }
        }
        return false;
    };
    
    std::vector<int> current;
    std::set<int> used_types;
    
    // Try starting with each possible first number
    for (int t = 3; t <= 8; ++t) {
        for (int num : polys[t]) {
            current = {num};
            used_types = {t};
            if (find_cycle(current, used_types, num / 100)) {
                // Found
                int sum = 0;
                for (int n : current) sum += n;
                return sum;
            }
        }
    }
    
    return -1; // Not found
}

#if ! defined UNITTEST_MODE
int main(int argc, char const *argv[]) {
    std::cout << cyclical_figurate_numbers() << std::endl;
}
#endif // UNITTEST_MODE