// https://projecteuler.net/problem=29
//
// Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
// 2^2=4, 2^3=8, 2^4=16, 2^5=32
// 3^2=9, 3^3=27, 3^4=81, 3^5=243
// 4^2=16, 4^3=64, 4^4=256, 4^5=1024
// 5^2=25, 5^3=125, 5^4=625, 5^5=3125
//
// If they are then placed in numerical order, with any repeats removed, we get a
// sequence of 15 distinct terms.
//
// How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 5 and
// 2 ≤ b ≤ 5? (Problem asks for 2 ≤ a,b ≤ 100)
//
// Answer: 9183

fn multiply_vec(digits: &[u32], factor: u64) -> Vec<u32> {
    let mut result = digits.to_vec();
    let mut carry = 0u64;
    for d in result.iter_mut() {
        let val = *d as u64 * factor + carry;
        *d = (val % 10) as u32;
        carry = val / 10;
    }
    while carry > 0 {
        result.push((carry % 10) as u32);
        carry /= 10;
    }
    result
}

pub fn distinct_powers(limit: u64) -> usize {
    use std::collections::HashSet;
    let mut seen: HashSet<Vec<u32>> = HashSet::new();
    for a in 2..=limit {
        let mut power = vec![1u32];
        for b in 1..=limit {
            power = multiply_vec(&power, a);
            if b >= 2 {
                seen.insert(power.clone());
            }
        }
    }
    seen.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn euler_029() {
        assert_eq!(distinct_powers(5), 15);
        assert_eq!(distinct_powers(100), 9183);
    }
}
