// https://projecteuler.net/problem=12
//
// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
//
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have over five hundred divisors?
//
// Answer: 76576500

fn divisor_count(n: u64) -> usize {
    let mut count = 0;
    let sqrt_n = (n as f64).sqrt() as u64;
    for i in 1..=sqrt_n {
        if n % i == 0 {
            count += 2;
            if i == n / i {
                count -= 1;
            }
        }
    }
    count
}

pub fn highly_divisible_triangular_number(min_divisors: usize) -> u64 {
    let mut n = 1u64;
    loop {
        let triangular = n * (n + 1) / 2;
        if divisor_count(triangular) > min_divisors {
            return triangular;
        }
        n += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn euler_012() {
        assert_eq!(highly_divisible_triangular_number(5), 28);
        assert_eq!(highly_divisible_triangular_number(500), 76_576_500);
    }
}