// https://projecteuler.net/problem=45
//
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
//
// It can be verified that T285 = P165 = H143 = 40755.
// Find the next triangle number that is also pentagonal and hexagonal.
//
// Answer: 1533776805

pub fn triangular_pentagonal_hexagonal() -> u64 {
    // Hexagonal numbers are also triangular: Hn = n(2n-1) = Tn for some n
    // Every hexagonal is also triangular.
    // So need Hn that is also pentagonal.
    // Hn = n(2n-1)
    // Pn = m(3m-1)/2
    // Set equal: n(2n-1) = m(3m-1)/2
    // Solve for integers n,m >143 (since H143=40755)
    let mut n = 144;
    loop {
        let h = n * (2 * n - 1);
        // Check if h is pentagonal
        // m(3m-1)/2 = h => 3m^2 - m - 2h = 0
        let discriminant = 1 + 24 * h;
        let sqrt_disc = (discriminant as f64).sqrt() as u64;
        if sqrt_disc * sqrt_disc == discriminant && (sqrt_disc + 1) % 6 == 0 {
            return h;
        }
        n += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn euler_045() {
        assert_eq!(triangular_pentagonal_hexagonal(), 1533776805);
    }
}