// https://projecteuler.net/problem=61

// Cyclical Figurate Numbers

// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
// Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...
// Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...
// Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...
// Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...
// Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...
// Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...
// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
// 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
// 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
// 3. This is the only set of 4-digit numbers with this property.
// Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

// Answer: 28684

pub fn cyclical_figurate_numbers() -> u32 {
    let mut polys: Vec<Vec<u32>> = vec![vec![]; 9];
    
    let mut gen_poly = |typ: usize, formula: fn(usize) -> u32| {
        for n in 1.. {
            let num = formula(n);
            if num >= 10000 { break; }
            if num >= 1000 { polys[typ].push(num); }
        }
    };
    
    gen_poly(3, |n| (n * (n + 1) / 2) as u32);
    gen_poly(4, |n| (n * n) as u32);
    gen_poly(5, |n| (n * (3 * n - 1) / 2) as u32);
    gen_poly(6, |n| (n * (2 * n - 1)) as u32);
    gen_poly(7, |n| (n * (5 * n - 3) / 2) as u32);
    gen_poly(8, |n| (n * (3 * n - 2)) as u32);
    
    let mut by_prefix: Vec<Vec<Vec<u32>>> = vec![vec![vec![]; 100]; 9];
    for t in 3..=8 {
        for &num in &polys[t] {
            let prefix = (num / 100) as usize;
            by_prefix[t][prefix].push(num);
        }
    }
    
    fn find_cycle(current: &mut Vec<u32>, used: &mut std::collections::HashSet<usize>, by_prefix: &Vec<Vec<Vec<u32>>>) -> Option<u32> {
        if current.len() == 6 {
            let last = (current[current.len() - 1] % 100) as usize;
            let first = (current[0] / 100) as usize;
            if last == first {
                return Some(current.iter().sum());
            }
            return None;
        }
        let next_prefix = (current[current.len() - 1] % 100) as usize;
        for t in 3..=8 {
            if used.contains(&t) { continue; }
            for &num in &by_prefix[t][next_prefix] {
                current.push(num);
                used.insert(t);
                if let Some(sum) = find_cycle(current, used, by_prefix) {
                    return Some(sum);
                }
                used.remove(&t);
                current.pop();
            }
        }
        None
    }
    
    for t in 3..=8 {
        for &num in &polys[t] {
            let mut current = vec![num];
            let mut used = std::collections::HashSet::new();
            used.insert(t);
            if let Some(sum) = find_cycle(&mut current, &mut used, &by_prefix) {
                return sum;
            }
        }
    }
    0
}