// https://projecteuler.net/problem=44
//
// Pentagon numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
//
// Answer: 5482660

pub fn pentagon_numbers() -> u64 {
    let mut pentagons = Vec::new();
    let mut n = 1;
    loop {
        let p = n * (3 * n - 1) / 2;
        if p > 10_000_000 { break; } // arbitrary large limit
        pentagons.push(p);
        n += 1;
    }
    let pent_set: std::collections::HashSet<u64> = pentagons.iter().cloned().collect();

    let mut min_d = u64::MAX;
    for i in 0..pentagons.len() {
        for j in (i+1)..pentagons.len() {
            let pj = pentagons[i];
            let pk = pentagons[j];
            let sum = pj + pk;
            let diff = pk - pj;
            if pent_set.contains(&sum) && pent_set.contains(&diff) {
                if diff < min_d {
                    min_d = diff;
                }
            }
        }
    }
    min_d
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn euler_044() {
        assert_eq!(pentagon_numbers(), 5482660);
    }
}