def solve():
    """
    Pentagon Numbers
    Pentagon numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, …

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
    https://projecteuler.net/problem=44
    """
    def is_pentagonal(n):
        disc = 1 + 24 * n
        sqrt_d = int(disc ** 0.5 + 0.5)
        if sqrt_d * sqrt_d == disc:
            k = (1 + sqrt_d) // 6
            return k * (3 * k - 1) // 2 == n
        return False

    pent = []
    i = 1
    while True:
        p = i * (3 * i - 1) // 2
        pent.append(p)
        for j in range(len(pent) - 2, -1, -1):
            diff = p - pent[j]
            summ = p + pent[j]
            if is_pentagonal(diff) and is_pentagonal(summ):
                return diff
        i += 1