# Problem 61: Cyclical Figurate Numbers
# Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
# Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...
# Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...
# Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...
# Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...
# Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...
# Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...
# The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
# 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
# 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
# 3. This is the only set of 4-digit numbers with this property.
# Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
# Answer: 28684
# Execution time: About 0.01 seconds
# Optimizations: Generate all 4-digit polygonal numbers, use prefix maps for efficient lookup, backtracking to find cyclic chain
# Notes: AI-generated solution using combinatorial search with early termination

def gen_poly(typ):
    polys = []
    n = 1
    while True:
        if typ == 3:
            num = n * (n + 1) // 2
        elif typ == 4:
            num = n * n
        elif typ == 5:
            num = n * (3 * n - 1) // 2
        elif typ == 6:
            num = n * (2 * n - 1)
        elif typ == 7:
            num = n * (5 * n - 3) // 2
        elif typ == 8:
            num = n * (3 * n - 2)
        if num >= 10000:
            break
        if num >= 1000:
            polys.append(num)
        n += 1
    return polys

def solve():
    polys = [[] for _ in range(9)]
    for t in range(3, 9):
        polys[t] = gen_poly(t)

    by_prefix = [[[] for _ in range(100)] for _ in range(9)]
    for t in range(3, 9):
        for num in polys[t]:
            prefix = num // 100
            by_prefix[t][prefix].append(num)

    def find_cycle(current, used, start_prefix):
        if len(current) == 6:
            last = current[-1] % 100
            first = current[0] // 100
            if last == first:
                return sum(current)
            return -1
        next_prefix = current[-1] % 100
        for t in range(3, 9):
            if t in used:
                continue
            for num in by_prefix[t][next_prefix]:
                current.append(num)
                used.add(t)
                res = find_cycle(current, used, start_prefix)
                if res != -1:
                    return res
                used.remove(t)
                current.pop()
        return -1

    for t in range(3, 9):
        for num in polys[t]:
            current = [num]
            used = set([t])
            res = find_cycle(current, used, num // 100)
            if res != -1:
                return res
    return -1