def solve():
    """
    Highly divisible triangular number
    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
    The number 28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?
    """
    def num_divisors(n):
        count = 0
        for i in range(1, int(n**0.5) + 1):
            if n % i == 0:
                count += 2 if i != n // i else 1
        return count

    i = 1
    triangle = 0
    while True:
        triangle += i
        if num_divisors(triangle) > 500:
            return triangle
        i += 1