def solve():
    """
    Triangular, Pentagonal, and Hexagonal
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

    Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...

    Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...

    Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
    https://projecteuler.net/problem=45
    """
    def is_pentagonal(n):
        disc = 1 + 24 * n
        sqrt_d = int(disc ** 0.5 + 0.5)
        if sqrt_d * sqrt_d == disc:
            k = (1 + sqrt_d) // 6
            return k * (3 * k - 1) // 2 == n
        return False

    def is_hexagonal(n):
        disc = 1 + 8 * n
        sqrt_d = int(disc ** 0.5 + 0.5)
        if sqrt_d * sqrt_d == disc:
            k = (1 + sqrt_d) // 4
            return k * (2 * k - 1) == n
        return False

    n = 286
    while True:
        t = n * (n + 1) // 2
        if is_pentagonal(t) and is_hexagonal(t):
            return t
        n += 1