// https://projecteuler.net/problem=45

/*

Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2        1, 3, 6, 10, 15, ...

Pentagonal    Pn=n(3n-1)/2        1, 5, 12, 22, 35, ...

Hexagonal    Hn=n(2n-1)            1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Answer: 1533776805

*/

package main

import "fmt"

import "math"

func isPentagonal(n int) bool {
	disc := 1 + 24*n
	k := int((1 + math.Sqrt(float64(disc))) / 6)
	return k*(3*k-1)/2 == n
}

func isHexagonal(n int) bool {
	disc := 1 + 8*n
	k := int((1 + math.Sqrt(float64(disc))) / 4)
	return k*(2*k-1) == n
}

func main() {
	n := 286
	for {
		t := n * (n + 1) / 2
		if isPentagonal(t) && isHexagonal(t) {
			fmt.Println(t)
			return
		}
		n++
	}
}