// https://projecteuler.net/problem=61

// Cyclical Figurate Numbers

// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
// Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...
// Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...
// Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...
// Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...
// Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...
// Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...
// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
// 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
// 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
// 3. This is the only set of 4-digit numbers with this property.
// Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

// Answer: 28684

// Execution time: ~69ms on modern hardware

// Optimizations: Generate all 4-digit polygonal numbers, use prefix maps for efficient lookup, backtracking to find cyclic chain
// Interesting notes: AI-generated solution using combinatorial search with early termination

package main

import "fmt"

func genPoly(typ int) []int {
	polys := []int{}
	for n := 1; ; n++ {
		var num int
		switch typ {
		case 3:
			num = n * (n + 1) / 2
		case 4:
			num = n * n
		case 5:
			num = n * (3*n - 1) / 2
		case 6:
			num = n * (2*n - 1)
		case 7:
			num = n * (5*n - 3) / 2
		case 8:
			num = n * (3*n - 2)
		}
		if num >= 10000 {
			break
		}
		if num >= 1000 {
			polys = append(polys, num)
		}
	}
	return polys
}

func cyclicalFigurateNumbers() int {
	polys := make([][]int, 9)
	for t := 3; t <= 8; t++ {
		polys[t] = genPoly(t)
	}

	byPrefix := make([][][]int, 9)
	for t := 3; t <= 8; t++ {
		byPrefix[t] = make([][]int, 100)
		for _, num := range polys[t] {
			prefix := num / 100
			byPrefix[t][prefix] = append(byPrefix[t][prefix], num)
		}
	}

	var findCycle func([]int, map[int]bool, int) int
	findCycle = func(current []int, used map[int]bool, startPrefix int) int {
		if len(current) == 6 {
			last := current[len(current)-1] % 100
			first := current[0] / 100
			if last == first {
				sum := 0
				for _, n := range current {
					sum += n
				}
				return sum
			}
			return -1
		}
		nextPrefix := current[len(current)-1] % 100
		for t := 3; t <= 8; t++ {
			if used[t] {
				continue
			}
			for _, num := range byPrefix[t][nextPrefix] {
				newCurrent := append([]int(nil), current...)
				newCurrent = append(newCurrent, num)
				newUsed := make(map[int]bool)
				for k, v := range used {
					newUsed[k] = v
				}
				newUsed[t] = true
				if res := findCycle(newCurrent, newUsed, startPrefix); res != -1 {
					return res
				}
			}
		}
		return -1
	}

	for t := 3; t <= 8; t++ {
		for _, num := range polys[t] {
			current := []int{num}
			used := map[int]bool{t: true}
			if res := findCycle(current, used, num/100); res != -1 {
				return res
			}
		}
	}
	return -1
}

func main() {
	fmt.Println(cyclicalFigurateNumbers())
}