// https://projecteuler.net/problem=44

/*

Pentagon Numbers

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, …

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

Answer: 5482660

*/

// Optimized implementation:
// - Uses big.Int for precise integer square root to avoid floating-point errors in isPentagonal.
// - Generates pentagonals sequentially until the pair is found, with early termination at n=10000.
// - Time: O(n^2) with fast pentagonal checks, finds answer quickly.
// - Space: O(n) for the slice of pentagonals.
package main

import "fmt"

import "math/big"

func isPentagonal(n int) bool {
	disc := big.NewInt(1 + 24*int64(n))
	sqrtD := new(big.Int).Sqrt(disc)
	sq := new(big.Int).Mul(sqrtD, sqrtD)
	if sq.Cmp(disc) != 0 {
		return false
	}
	k := new(big.Int).Add(sqrtD, big.NewInt(1))
	k.Div(k, big.NewInt(6))
	p := new(big.Int).Mul(k, big.NewInt(3))
	p.Sub(p, big.NewInt(1))
	p.Mul(p, k)
	p.Div(p, big.NewInt(2))
	return p.Cmp(big.NewInt(int64(n))) == 0
}

func main() {
	var pents []int
	for n := 1; ; n++ {
		if n > 10000 {
			fmt.Println("Pair not found within limit")
			return
		}
		p := n * (3*n - 1) / 2
		pents = append(pents, p)
		for j := 0; j < len(pents)-1; j++ {
			pj := pents[j]
			diff := p - pj
			sum := p + pj
			if isPentagonal(diff) && isPentagonal(sum) {
				fmt.Println(diff)
				return
			}
		}
	}
}