/*
 * Solution for Euler problem 045
 *
 * Triangular, Pentagonal, and Hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
 * Pentagonal   Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
 * Hexagonal   Hn=n(2n-1)   1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * @author tvarley
 * @date 3/14/2026
 */
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;

public class Solution045 implements Solution {
  public String solve() {
    long n = 144;
    while (true) {
      long hn = n * (2 * n - 1);
      if (isPentagonal(hn) && isTriangular(hn)) {
        return Long.toString(hn);
      }
      n++;
    }
  }

  private boolean isPentagonal(long n) {
    long k = (long) ((1 + Math.sqrt(1 + 24 * n)) / 6);
    return k * (3 * k - 1) / 2 == n;
  }

  private boolean isTriangular(long n) {
    long k = (long) (( -1 + Math.sqrt(1 + 8 * n)) / 2);
    return k * (k + 1) / 2 == n;
  }
}