/*
 * Solution for Euler problem 029
 *
 * Distinct powers
 *
 * Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5.
 * If they are then placed in numerical order, with any repeats removed, there
 * are 15 distinct terms.
 *
 * How many distinct terms are in the sequence generated by a^b for
 * 2 <= a <= 100 and 2 <= b <= 100?
 *
 * @author tvarley
 * @date 3/8/2026
 */
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

public class Solution029 implements Solution {
  public String solve() {
    Set<BigInteger> distinct = new HashSet<>();

    for (int a = 2; a <= 100; a++) {
      for (int b = 2; b <= 100; b++) {
        distinct.add(BigInteger.valueOf(a).pow(b));
      }
    }

    return Integer.toString(distinct.size());
  }
}
