/*
 * Solution for Euler problem 012
 *
 * Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * @author tvarley
 * @date 3/8/2026
 */
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;

public class Solution012 implements Solution {
  public String solve() {
    long n = 1;
    while (true) {
      long triangle = n * (n + 1) / 2;
      if (countDivisors(triangle) > 500) {
        return Long.toString(triangle);
      }
      n++;
    }
  }

  private int countDivisors(long number) {
    int count = 0;
    for (long i = 1; i * i <= number; i++) {
      if (number % i == 0) {
        count += (i * i == number) ? 1 : 2;
      }
    }
    return count;
  }
}