/*
 * Solution for Euler problem 044
 *
 * Pentagon Numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
 *
 * @author tvarley
 * @date 3/14/2026
 */
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;
import java.util.HashSet;
import java.util.Set;

public class Solution044 implements Solution {
  public String solve() {
    Set<Long> pents = new HashSet<>();
    long minD = Long.MAX_VALUE;
    for (long k = 1; k < 3000; k++) {
      long pk = k * (3 * k - 1) / 2;
      for (long pj : pents) {
        long diff = pk - pj;
        long sum = pk + pj;
        if (pents.contains(diff) && isPentagonal(sum)) {
          if (diff < minD) minD = diff;
        }
      }
      pents.add(pk);
    }
    return Long.toString(minD);
  }

  private boolean isPentagonal(long n) {
    long k = (long) ((1 + Math.sqrt(1 + 24 * n)) / 6);
    return k * (3 * k - 1) / 2 == n;
  }
}