/*
Cyclical Figurate Numbers

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...

Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...

Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...

Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...

Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...

Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).

2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.

3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

The final answer to the problem is 28684.

Execution time measurements: Approximately 50 ms on standard hardware.

Details on any optimizations made during development: Generate all 4-digit polygonal numbers, use prefix maps for efficient lookup, backtracking to find cyclic chain

Interesting notes or insights from the AI implementation process: AI-generated solution using combinatorial search with early termination
*/
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;
import java.util.*;

public class Solution061 implements Solution {
  public String solve() {
    List<List<Integer>> polys = new ArrayList<>();
    for (int i = 0; i < 9; i++) polys.add(new ArrayList<>());

    // Generate polygonal numbers
    for (int t = 3; t <= 8; t++) {
      for (int n = 1; ; n++) {
        int num;
        switch (t) {
          case 3: num = n * (n + 1) / 2; break;
          case 4: num = n * n; break;
          case 5: num = n * (3 * n - 1) / 2; break;
          case 6: num = n * (2 * n - 1); break;
          case 7: num = n * (5 * n - 3) / 2; break;
          case 8: num = n * (3 * n - 2); break;
          default: num = 0;
        }
        if (num >= 10000) break;
        if (num >= 1000) polys.get(t).add(num);
      }
    }

    // Create by_prefix
    List<List<List<Integer>>> byPrefix = new ArrayList<>();
    for (int t = 3; t <= 8; t++) {
      List<List<Integer>> prefixes = new ArrayList<>();
      for (int p = 0; p < 100; p++) prefixes.add(new ArrayList<>());
      for (int num : polys.get(t)) {
        int prefix = num / 100;
        prefixes.get(prefix).add(num);
      }
      byPrefix.add(prefixes);
    }

    // Find cycle
    int[] result = new int[1];
    for (int t = 3; t <= 8; t++) {
      for (int num : polys.get(t)) {
        List<Integer> current = new ArrayList<>();
        current.add(num);
        Set<Integer> used = new HashSet<>();
        used.add(t);
        if (findCycle(current, used, byPrefix, num / 100, result)) {
          return String.valueOf(result[0]);
        }
      }
    }
    return "0";
  }

  private boolean findCycle(List<Integer> current, Set<Integer> used, List<List<List<Integer>>> byPrefix, int startPrefix, int[] result) {
    if (current.size() == 6) {
      int last = current.get(current.size() - 1) % 100;
      int first = current.get(0) / 100;
      if (last == first) {
        result[0] = current.stream().mapToInt(Integer::intValue).sum();
        return true;
      }
      return false;
    }
    int nextPrefix = current.get(current.size() - 1) % 100;
    for (int t = 3; t <= 8; t++) {
      if (used.contains(t)) continue;
      for (int num : byPrefix.get(t - 3).get(nextPrefix)) {
        current.add(num);
        used.add(t);
        if (findCycle(current, used, byPrefix, startPrefix, result)) return true;
        used.remove(t);
        current.remove(current.size() - 1);
      }
    }
    return false;
  }
}