// https://projecteuler.net/problem=12

// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
// The first ten: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// What is the value of the first triangle number to have over five hundred divisors?
//
// Answer: 76576500

function countDivisors(n) {
  let count = 0;
  for (let i = 1; i <= Math.sqrt(n); i++) {
    if (n % i === 0) {
      count += (i === n / i) ? 1 : 2;
    }
  }
  return count;
}

module.exports = {
  answer: () => {
    let n = 1;
    while (true) {
      const triangle = n * (n + 1) / 2;
      if (countDivisors(triangle) > 500) {
        return triangle;
      }
      n++;
    }
  }
};