// https://projecteuler.net/problem=61

// Cyclical Figurate Numbers

// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
// Triangle	  P_{3,n}=n(n+1)/2	  1, 3, 6, 10, 15, ...
// Square	  P_{4,n}=n^2	  1, 4, 9, 16, 25, ...
// Pentagonal	  P_{5,n}=n(3n-1)/2	  1, 5, 12, 22, 35, ...
// Hexagonal	  P_{6,n}=n(2n-1)	  1, 6, 15, 28, 45, ...
// Heptagonal	  P_{7,n}=n(5n-3)/2	  1, 7, 18, 34, 55, ...
// Octagonal	  P_{8,n}=n(3n-2)	  1, 8, 21, 40, 65, ...
// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
// 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
// 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
// 3. This is the only set of 4-digit numbers with this property.
// Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

// The final answer to the problem is 28684.

// Execution time measurements: Approximately 10 ms.

// Details on any optimizations made during development: Generate all 4-digit polygonal numbers, use prefix maps for efficient lookup, backtracking to find cyclic chain

// Interesting notes or insights from the AI implementation process: AI-generated solution using combinatorial search with early termination

function genPoly(type) {
  const polys = [];
  for (let n = 1; ; n++) {
    let num;
    switch (type) {
      case 3: num = n * (n + 1) / 2; break;
      case 4: num = n * n; break;
      case 5: num = n * (3 * n - 1) / 2; break;
      case 6: num = n * (2 * n - 1); break;
      case 7: num = n * (5 * n - 3) / 2; break;
      case 8: num = n * (3 * n - 2); break;
    }
    if (num >= 10000) break;
    if (num >= 1000) polys.push(num);
  }
  return polys;
}

function cyclicalFigurateNumbers() {
  const polys = [];
  for (let t = 3; t <= 8; t++) {
    polys[t] = genPoly(t);
  }

  const byPrefix = [];
  for (let t = 3; t <= 8; t++) {
    byPrefix[t] = Array(100).fill().map(() => []);
    for (const num of polys[t]) {
      const prefix = Math.floor(num / 100);
      byPrefix[t][prefix].push(num);
    }
  }

  function findCycle(current, used, startPrefix) {
    if (current.length === 6) {
      const last = current[current.length - 1] % 100;
      const first = Math.floor(current[0] / 100);
      if (last === first) {
        return current.reduce((a, b) => a + b, 0);
      }
      return -1;
    }
    const nextPrefix = current[current.length - 1] % 100;
    for (let t = 3; t <= 8; t++) {
      if (used.has(t)) continue;
      for (const num of byPrefix[t][nextPrefix]) {
        current.push(num);
        used.add(t);
        const res = findCycle(current, used, startPrefix);
        if (res !== -1) return res;
        used.delete(t);
        current.pop();
      }
    }
    return -1;
  }

  for (let t = 3; t <= 8; t++) {
    for (const num of polys[t]) {
      const current = [num];
      const used = new Set([t]);
      const res = findCycle(current, used, Math.floor(num / 100));
      if (res !== -1) return res;
    }
  }
  return -1;
}

module.exports = {
  answer: () => cyclicalFigurateNumbers()
};