// https://projecteuler.net/problem=45

// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
// Find the next triangle number that is also pentagonal and hexagonal.

// Answer: 1533776805

const isPentagonal = (n) => {
  const k = (1 + Math.sqrt(1 + 24 * n)) / 6;
  return k === Math.floor(k);
};

module.exports = {
  answer: () => {
    let m = 144;
    while (true) {
      const h = m * (2 * m - 1);
      if (isPentagonal(h)) {
        return h;
      }
      m++;
    }
  }
};