// https://projecteuler.net/problem=44

// Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

// Answer: 5482660

const isPentagonal = (n) => {
  const k = (1 + Math.sqrt(1 + 24 * n)) / 6;
  return k === Math.floor(k);
};

module.exports = {
  answer: () => {
    const pentagonals = [];
    let i = 1;
    while (true) {
      const p = i * (3 * i - 1) / 2;
      pentagonals.push(p);
      for (let j = 0; j < pentagonals.length - 1; j++) {
        const pj = pentagonals[j];
        const pk = p;
        const sum = pj + pk;
        const diff = pk - pj;
        if (isPentagonal(sum) && isPentagonal(diff)) {
          return diff;
        }
      }
      i++;
    }
  }
};